# -*- coding: utf-8 -*-
"""CPVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_mpMJsFjrJd0QHEKyCwsY464pAD5x9P
"""

#RULES:
#1. VARIABLE_VALUE opcode must always come before VARIABLE_NAME opcode.
#2. For every control flow there must be JUMP_IF_TRUE and JUMP_IF_FALSE opcode.
class VirtualMachine:
  def __init__(self, byteCode):
    self.byteCode = byteCode
    self.stack = []
    self.memory = {}
    self.LP = 0

  def runVM(self):
    if len(self.byteCode) < 2:
      raise RuntimeError("Not enough values on bytecode")

    while self.LP < len(self.byteCode):
      instruction, value = self.byteCode[self.LP]

      if instruction == "LOAD_NUMBER":
        self.stack.append(value)

      elif instruction == "LOAD_STRING":
        self.stack.append(value)

      elif instruction == "VARIABLE_VALUE":
        self.stack.append(value)

      elif instruction == "VARIABLE_NAME":
        self.memory[value] = self.stack.pop()

      elif instruction == "ADDITION":
        x = self.stack.pop()
        y = self.stack.pop()
        result = x + y
        self.stack.append(result)

      elif instruction == "SUBTRACTION":
        x = self.stack.pop()
        y = self.stack.pop()
        result = x - y
        self.stack.append(result)

      elif instruction == "MULTIPLICATION":
        x = self.stack.pop()
        y = self.stack.pop()
        result = x * y
        self.stack.append(result)

      elif instruction == "DIVISION":
        x = self.stack.pop()
        y = self.stack.pop()
        if y == 0:
          raise ZeroDivisionError("Can't divide by zero")
        else:
          result = x / y
        self.stack.append(result)

      elif instruction == "SQUARE":
        x = self.stack.pop()
        y = self.stack.pop()
        result = x ** y
        self.stack.append(result)

      elif instruction == "FLOOR_DIVISION":
        x = self.stack.pop()
        y = self.stack.pop()
        if y == 0:
          raise ZeroDivisionError("Can't divide by zero")
        else:
          result = x // y
        self.stack.append(result)

      elif instruction == "REMAINING":
        x = self.stack.pop()
        y = self.stack.pop()
        if y == 0:
          raise ZeroDivisionError("Can't divide by zero")
        else:
          result = x % y
        self.stack.append(result)

      elif instruction == "GREATER_THAN":
        x = self.stack.pop()
        y = self.stack.pop()
        result = x < y
        self.stack.append(result)

      elif instruction == "LESS_THAN":
        x = self.stack.pop()
        y = self.stack.pop()
        result = x > y

        self.stack.append(result)

      elif instruction == "EQUAL_TO":
        x = self.stack.pop()
        y = self.stack.pop()
        result = y == x
        self.stack.append(result)

      elif instruction == "JUMP_IF_FALSE":
        condition = self.stack.pop()
        if condition == False:
          self.LP = value
          continue

      elif instruction == "JUMP_IF_TRUE":
        self.LP = value
        continue

      elif instruction == "PRINT":
        result = self.stack.pop()
        print(result)

      elif instruction == "LOAD_VARIABLE":
        if value not in self.memory:
          raise NameError("The Variable is not found!!")
        variableValue = self.memory[value]
        self.stack.append(variableValue)

      else:
        print("The instruction is not valid according to Kidus's Python Virtual Machine.")
      self.LP += 1

program = [
    ("LOAD_STRING", "Hello"),
    ("PRINT", None)
]
vm = VirtualMachine(program)
vm.runVM()